server.port=8081
spring.application.name=task-service-users-async
management.endpoints.web.base-path=/producer/consumer/users/v1/actuator
management.endpoints.enabled-by-default=false
management.endpoint.health.enabled=true
management.endpoint.info.enabled=true

#Kafka Connection SuperApp or Local
bootstrap.server=kiobadevntzkeo2.dev-ecobok.confluent.corp:9093,kiobadevntbkeo1.dev-ecobok.confluent.corp:9093,kiobadevntbkeo2.dev-ecobok.confluent.corp:9093

#Url de schema registry
schema.registry.url=https://kiobadevntzkeo2.dev-ecobok.confluent.corp:8081

#checarlamusic
avro.specific.reader=true

# Kafka Groups & Topics
topic.name=TP-BAZ-ABONO-CREDITO-COBRANZA-V1-PAGOS-CREDITOS-ADD

# Kafka Groups & Topics
consumer.group.id=GR-SAGO-TP-BAZ-ABONO-CREDITO-COBRANZA-V1-PAGOS-CREDITOS-ADD
#consumer.group.id=GR-PRUEBAS-VALIDACIÓN-CONSUMO-V1
##auto_offset_reset latest , earliest
auto.offset.reset=earliest


#Encriptado y desencriptado

#llaves nuevas de dev
dec.key = rqjjMb+Px0cg5qtxvK7y3ifNyfkCqsl7VIfTbyb/mHQ=
dec.iv = DnpbZYr58FbDD/DJNnnTa5dAZ6Z2aCF4XN2Av+vEA3s=

dec.AESKEY = AES
dec.ALGORITHM = AES/GCM/NoPadding


#Kafka Connection Seguridad
#protocolo de seguridad
protocol.securtity=SSL

#path del keystore
path.keystore=certs/kiobadevntzkeo2.dev-ecobok.confluent.corp.keystore.jks

#password keystore
keystore.password=C0nflu3ntBoK


#path del truestore
path.truestore=certs/kiobadevntzkeo2.dev-ecobok.confluent.corp.server.truststore.jks

#password truststore
truststore.password=C0nflu3ntBoK


db.url=jdbc:oracle:thin:@//rds-oracle-sago-dev.caynatckvznu.us-east-1.rds.amazonaws.com:3306/bdsagode
db.username=admin
db.password=20204dm1N$Ag0DBMi$Q1
db.driver=oracle.jdbc.OracleDriver








