server.port=8081
spring.application.name=task-service-users-async
management.endpoints.web.base-path=/producer/consumer/users/v1/actuator
management.endpoints.enabled-by-default=false
management.endpoint.health.enabled=true
management.endpoint.info.enabled=true

#Kafka Connection SuperApp or Local
bootstrap.server=ecobroker01.prod-ecobok.confluent.corp:9093,ecobroker02.prod-ecobok.confluent.corp:9093,ecobroker03.prod-ecobok.confluent.corp:9093,ecobroker04.prod-ecobok.confluent.corp:9093,ecobroker05.prod-ecobok.confluent.corp:9093

#Url de schema registry
schema.registry.url=https://ecoregistry01.prod-ecobok.confluent.corp:8081,https://ecoregistry02.prod-ecobok.confluent.corp:8081

#checarlamusic
avro.specific.reader=true

# Kafka Groups & Topics
topic.name=TP-BAZ-ABONO-CREDITO-COBRANZA-V1-PAGOS-CREDITOS-ADD

# Kafka Groups & Topics
consumer.group.id=GR-SAGO-CREDITO-TP-BAZ-ABONO-CREDITO-COBRANZA-V1-PAGOS-CREDITOS-ADD
#consumer.group.id=GR-PRUEBAS-VALIDACIÓN-CONSUMO-V1
##auto_offset_reset latest , earliest
auto.offset.reset=earliest


#Encriptado y desencriptado

#llaves nuevas de dev
dec.key = rqjjMb+Px0cg5qtxvK7y3ifNyfkCqsl7VIfTbyb/mHQ=
dec.iv = DnpbZYr58FbDD/DJNnnTa5dAZ6Z2aCF4XN2Av+vEA3s=

dec.AESKEY = AES
dec.ALGORITHM = AES/GCM/NoPadding


#Kafka Connection Seguridad
#protocolo de seguridad
protocol.securtity=SSL

#path del keystore
path.keystore=certs/sago-credito-cobranza.keystore.jks

#password keystore
keystore.password=S4G0LP4


#path del truestore
path.truestore=certs/sago-credito-cobranza.truststore.jks

#password truststore
truststore.password=S4G0LP4


db.url=jdbc:oracle:thin:@//rds-oracle-prod.cekeq8einymu.us-east-1.rds.amazonaws.com:4410/ORCL
db.username=USRSAGINSUM
db.password=U5rG3nINS0#
db.driver=oracle.jdbc.OracleDriver








