/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.gs.atc.bok.schemaRegistry;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class ClienteUnico extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -1624105624662686499L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"ClienteUnico\",\"namespace\":\"com.gs.atc.bok.schemaRegistry\",\"fields\":[{\"name\":\"pais\",\"type\":\"int\"},{\"name\":\"canal\",\"type\":\"int\"},{\"name\":\"sucursal\",\"type\":\"int\"},{\"name\":\"folio\",\"type\":\"int\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<ClienteUnico> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<ClienteUnico> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<ClienteUnico> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<ClienteUnico> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<ClienteUnico> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this ClienteUnico to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a ClienteUnico from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a ClienteUnico instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static ClienteUnico fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private int pais;
  private int canal;
  private int sucursal;
  private int folio;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public ClienteUnico() {}

  /**
   * All-args constructor.
   * @param pais The new value for pais
   * @param canal The new value for canal
   * @param sucursal The new value for sucursal
   * @param folio The new value for folio
   */
  public ClienteUnico(java.lang.Integer pais, java.lang.Integer canal, java.lang.Integer sucursal, java.lang.Integer folio) {
    this.pais = pais;
    this.canal = canal;
    this.sucursal = sucursal;
    this.folio = folio;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return pais;
    case 1: return canal;
    case 2: return sucursal;
    case 3: return folio;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: pais = (java.lang.Integer)value$; break;
    case 1: canal = (java.lang.Integer)value$; break;
    case 2: sucursal = (java.lang.Integer)value$; break;
    case 3: folio = (java.lang.Integer)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'pais' field.
   * @return The value of the 'pais' field.
   */
  public int getPais() {
    return pais;
  }


  /**
   * Sets the value of the 'pais' field.
   * @param value the value to set.
   */
  public void setPais(int value) {
    this.pais = value;
  }

  /**
   * Gets the value of the 'canal' field.
   * @return The value of the 'canal' field.
   */
  public int getCanal() {
    return canal;
  }


  /**
   * Sets the value of the 'canal' field.
   * @param value the value to set.
   */
  public void setCanal(int value) {
    this.canal = value;
  }

  /**
   * Gets the value of the 'sucursal' field.
   * @return The value of the 'sucursal' field.
   */
  public int getSucursal() {
    return sucursal;
  }


  /**
   * Sets the value of the 'sucursal' field.
   * @param value the value to set.
   */
  public void setSucursal(int value) {
    this.sucursal = value;
  }

  /**
   * Gets the value of the 'folio' field.
   * @return The value of the 'folio' field.
   */
  public int getFolio() {
    return folio;
  }


  /**
   * Sets the value of the 'folio' field.
   * @param value the value to set.
   */
  public void setFolio(int value) {
    this.folio = value;
  }

  /**
   * Creates a new ClienteUnico RecordBuilder.
   * @return A new ClienteUnico RecordBuilder
   */
  public static com.gs.atc.bok.schemaRegistry.ClienteUnico.Builder newBuilder() {
    return new com.gs.atc.bok.schemaRegistry.ClienteUnico.Builder();
  }

  /**
   * Creates a new ClienteUnico RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new ClienteUnico RecordBuilder
   */
  public static com.gs.atc.bok.schemaRegistry.ClienteUnico.Builder newBuilder(com.gs.atc.bok.schemaRegistry.ClienteUnico.Builder other) {
    if (other == null) {
      return new com.gs.atc.bok.schemaRegistry.ClienteUnico.Builder();
    } else {
      return new com.gs.atc.bok.schemaRegistry.ClienteUnico.Builder(other);
    }
  }

  /**
   * Creates a new ClienteUnico RecordBuilder by copying an existing ClienteUnico instance.
   * @param other The existing instance to copy.
   * @return A new ClienteUnico RecordBuilder
   */
  public static com.gs.atc.bok.schemaRegistry.ClienteUnico.Builder newBuilder(com.gs.atc.bok.schemaRegistry.ClienteUnico other) {
    if (other == null) {
      return new com.gs.atc.bok.schemaRegistry.ClienteUnico.Builder();
    } else {
      return new com.gs.atc.bok.schemaRegistry.ClienteUnico.Builder(other);
    }
  }

  /**
   * RecordBuilder for ClienteUnico instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<ClienteUnico>
    implements org.apache.avro.data.RecordBuilder<ClienteUnico> {

    private int pais;
    private int canal;
    private int sucursal;
    private int folio;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.gs.atc.bok.schemaRegistry.ClienteUnico.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.pais)) {
        this.pais = data().deepCopy(fields()[0].schema(), other.pais);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.canal)) {
        this.canal = data().deepCopy(fields()[1].schema(), other.canal);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.sucursal)) {
        this.sucursal = data().deepCopy(fields()[2].schema(), other.sucursal);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.folio)) {
        this.folio = data().deepCopy(fields()[3].schema(), other.folio);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
    }

    /**
     * Creates a Builder by copying an existing ClienteUnico instance
     * @param other The existing instance to copy.
     */
    private Builder(com.gs.atc.bok.schemaRegistry.ClienteUnico other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.pais)) {
        this.pais = data().deepCopy(fields()[0].schema(), other.pais);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.canal)) {
        this.canal = data().deepCopy(fields()[1].schema(), other.canal);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.sucursal)) {
        this.sucursal = data().deepCopy(fields()[2].schema(), other.sucursal);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.folio)) {
        this.folio = data().deepCopy(fields()[3].schema(), other.folio);
        fieldSetFlags()[3] = true;
      }
    }

    /**
      * Gets the value of the 'pais' field.
      * @return The value.
      */
    public int getPais() {
      return pais;
    }


    /**
      * Sets the value of the 'pais' field.
      * @param value The value of 'pais'.
      * @return This builder.
      */
    public com.gs.atc.bok.schemaRegistry.ClienteUnico.Builder setPais(int value) {
      validate(fields()[0], value);
      this.pais = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'pais' field has been set.
      * @return True if the 'pais' field has been set, false otherwise.
      */
    public boolean hasPais() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'pais' field.
      * @return This builder.
      */
    public com.gs.atc.bok.schemaRegistry.ClienteUnico.Builder clearPais() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'canal' field.
      * @return The value.
      */
    public int getCanal() {
      return canal;
    }


    /**
      * Sets the value of the 'canal' field.
      * @param value The value of 'canal'.
      * @return This builder.
      */
    public com.gs.atc.bok.schemaRegistry.ClienteUnico.Builder setCanal(int value) {
      validate(fields()[1], value);
      this.canal = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'canal' field has been set.
      * @return True if the 'canal' field has been set, false otherwise.
      */
    public boolean hasCanal() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'canal' field.
      * @return This builder.
      */
    public com.gs.atc.bok.schemaRegistry.ClienteUnico.Builder clearCanal() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'sucursal' field.
      * @return The value.
      */
    public int getSucursal() {
      return sucursal;
    }


    /**
      * Sets the value of the 'sucursal' field.
      * @param value The value of 'sucursal'.
      * @return This builder.
      */
    public com.gs.atc.bok.schemaRegistry.ClienteUnico.Builder setSucursal(int value) {
      validate(fields()[2], value);
      this.sucursal = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'sucursal' field has been set.
      * @return True if the 'sucursal' field has been set, false otherwise.
      */
    public boolean hasSucursal() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'sucursal' field.
      * @return This builder.
      */
    public com.gs.atc.bok.schemaRegistry.ClienteUnico.Builder clearSucursal() {
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'folio' field.
      * @return The value.
      */
    public int getFolio() {
      return folio;
    }


    /**
      * Sets the value of the 'folio' field.
      * @param value The value of 'folio'.
      * @return This builder.
      */
    public com.gs.atc.bok.schemaRegistry.ClienteUnico.Builder setFolio(int value) {
      validate(fields()[3], value);
      this.folio = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'folio' field has been set.
      * @return True if the 'folio' field has been set, false otherwise.
      */
    public boolean hasFolio() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'folio' field.
      * @return This builder.
      */
    public com.gs.atc.bok.schemaRegistry.ClienteUnico.Builder clearFolio() {
      fieldSetFlags()[3] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public ClienteUnico build() {
      try {
        ClienteUnico record = new ClienteUnico();
        record.pais = fieldSetFlags()[0] ? this.pais : (java.lang.Integer) defaultValue(fields()[0]);
        record.canal = fieldSetFlags()[1] ? this.canal : (java.lang.Integer) defaultValue(fields()[1]);
        record.sucursal = fieldSetFlags()[2] ? this.sucursal : (java.lang.Integer) defaultValue(fields()[2]);
        record.folio = fieldSetFlags()[3] ? this.folio : (java.lang.Integer) defaultValue(fields()[3]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<ClienteUnico>
    WRITER$ = (org.apache.avro.io.DatumWriter<ClienteUnico>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<ClienteUnico>
    READER$ = (org.apache.avro.io.DatumReader<ClienteUnico>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeInt(this.pais);

    out.writeInt(this.canal);

    out.writeInt(this.sucursal);

    out.writeInt(this.folio);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.pais = in.readInt();

      this.canal = in.readInt();

      this.sucursal = in.readInt();

      this.folio = in.readInt();

    } else {
      for (int i = 0; i < 4; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.pais = in.readInt();
          break;

        case 1:
          this.canal = in.readInt();
          break;

        case 2:
          this.sucursal = in.readInt();
          break;

        case 3:
          this.folio = in.readInt();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










