/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.gs.atc.bok.schemaRegistry;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class Transaccion extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 6699115179498326363L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Transaccion\",\"namespace\":\"com.gs.atc.bok.schemaRegistry\",\"fields\":[{\"name\":\"id\",\"type\":\"string\"},{\"name\":\"fechaHora\",\"type\":\"string\"},{\"name\":\"nombre\",\"type\":\"string\"},{\"name\":\"accion\",\"type\":\"string\"},{\"name\":\"fechaInicioProceso\",\"type\":\"string\"},{\"name\":\"fechaFinProceso\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Transaccion> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Transaccion> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<Transaccion> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<Transaccion> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<Transaccion> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this Transaccion to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a Transaccion from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a Transaccion instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static Transaccion fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.CharSequence id;
  private java.lang.CharSequence fechaHora;
  private java.lang.CharSequence nombre;
  private java.lang.CharSequence accion;
  private java.lang.CharSequence fechaInicioProceso;
  private java.lang.CharSequence fechaFinProceso;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Transaccion() {}

  /**
   * All-args constructor.
   * @param id The new value for id
   * @param fechaHora The new value for fechaHora
   * @param nombre The new value for nombre
   * @param accion The new value for accion
   * @param fechaInicioProceso The new value for fechaInicioProceso
   * @param fechaFinProceso The new value for fechaFinProceso
   */
  public Transaccion(java.lang.CharSequence id, java.lang.CharSequence fechaHora, java.lang.CharSequence nombre, java.lang.CharSequence accion, java.lang.CharSequence fechaInicioProceso, java.lang.CharSequence fechaFinProceso) {
    this.id = id;
    this.fechaHora = fechaHora;
    this.nombre = nombre;
    this.accion = accion;
    this.fechaInicioProceso = fechaInicioProceso;
    this.fechaFinProceso = fechaFinProceso;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return id;
    case 1: return fechaHora;
    case 2: return nombre;
    case 3: return accion;
    case 4: return fechaInicioProceso;
    case 5: return fechaFinProceso;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: id = (java.lang.CharSequence)value$; break;
    case 1: fechaHora = (java.lang.CharSequence)value$; break;
    case 2: nombre = (java.lang.CharSequence)value$; break;
    case 3: accion = (java.lang.CharSequence)value$; break;
    case 4: fechaInicioProceso = (java.lang.CharSequence)value$; break;
    case 5: fechaFinProceso = (java.lang.CharSequence)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'id' field.
   * @return The value of the 'id' field.
   */
  public java.lang.CharSequence getId() {
    return id;
  }


  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(java.lang.CharSequence value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'fechaHora' field.
   * @return The value of the 'fechaHora' field.
   */
  public java.lang.CharSequence getFechaHora() {
    return fechaHora;
  }


  /**
   * Sets the value of the 'fechaHora' field.
   * @param value the value to set.
   */
  public void setFechaHora(java.lang.CharSequence value) {
    this.fechaHora = value;
  }

  /**
   * Gets the value of the 'nombre' field.
   * @return The value of the 'nombre' field.
   */
  public java.lang.CharSequence getNombre() {
    return nombre;
  }


  /**
   * Sets the value of the 'nombre' field.
   * @param value the value to set.
   */
  public void setNombre(java.lang.CharSequence value) {
    this.nombre = value;
  }

  /**
   * Gets the value of the 'accion' field.
   * @return The value of the 'accion' field.
   */
  public java.lang.CharSequence getAccion() {
    return accion;
  }


  /**
   * Sets the value of the 'accion' field.
   * @param value the value to set.
   */
  public void setAccion(java.lang.CharSequence value) {
    this.accion = value;
  }

  /**
   * Gets the value of the 'fechaInicioProceso' field.
   * @return The value of the 'fechaInicioProceso' field.
   */
  public java.lang.CharSequence getFechaInicioProceso() {
    return fechaInicioProceso;
  }


  /**
   * Sets the value of the 'fechaInicioProceso' field.
   * @param value the value to set.
   */
  public void setFechaInicioProceso(java.lang.CharSequence value) {
    this.fechaInicioProceso = value;
  }

  /**
   * Gets the value of the 'fechaFinProceso' field.
   * @return The value of the 'fechaFinProceso' field.
   */
  public java.lang.CharSequence getFechaFinProceso() {
    return fechaFinProceso;
  }


  /**
   * Sets the value of the 'fechaFinProceso' field.
   * @param value the value to set.
   */
  public void setFechaFinProceso(java.lang.CharSequence value) {
    this.fechaFinProceso = value;
  }

  /**
   * Creates a new Transaccion RecordBuilder.
   * @return A new Transaccion RecordBuilder
   */
  public static com.gs.atc.bok.schemaRegistry.Transaccion.Builder newBuilder() {
    return new com.gs.atc.bok.schemaRegistry.Transaccion.Builder();
  }

  /**
   * Creates a new Transaccion RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Transaccion RecordBuilder
   */
  public static com.gs.atc.bok.schemaRegistry.Transaccion.Builder newBuilder(com.gs.atc.bok.schemaRegistry.Transaccion.Builder other) {
    if (other == null) {
      return new com.gs.atc.bok.schemaRegistry.Transaccion.Builder();
    } else {
      return new com.gs.atc.bok.schemaRegistry.Transaccion.Builder(other);
    }
  }

  /**
   * Creates a new Transaccion RecordBuilder by copying an existing Transaccion instance.
   * @param other The existing instance to copy.
   * @return A new Transaccion RecordBuilder
   */
  public static com.gs.atc.bok.schemaRegistry.Transaccion.Builder newBuilder(com.gs.atc.bok.schemaRegistry.Transaccion other) {
    if (other == null) {
      return new com.gs.atc.bok.schemaRegistry.Transaccion.Builder();
    } else {
      return new com.gs.atc.bok.schemaRegistry.Transaccion.Builder(other);
    }
  }

  /**
   * RecordBuilder for Transaccion instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Transaccion>
    implements org.apache.avro.data.RecordBuilder<Transaccion> {

    private java.lang.CharSequence id;
    private java.lang.CharSequence fechaHora;
    private java.lang.CharSequence nombre;
    private java.lang.CharSequence accion;
    private java.lang.CharSequence fechaInicioProceso;
    private java.lang.CharSequence fechaFinProceso;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.gs.atc.bok.schemaRegistry.Transaccion.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.fechaHora)) {
        this.fechaHora = data().deepCopy(fields()[1].schema(), other.fechaHora);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.nombre)) {
        this.nombre = data().deepCopy(fields()[2].schema(), other.nombre);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.accion)) {
        this.accion = data().deepCopy(fields()[3].schema(), other.accion);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.fechaInicioProceso)) {
        this.fechaInicioProceso = data().deepCopy(fields()[4].schema(), other.fechaInicioProceso);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.fechaFinProceso)) {
        this.fechaFinProceso = data().deepCopy(fields()[5].schema(), other.fechaFinProceso);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
    }

    /**
     * Creates a Builder by copying an existing Transaccion instance
     * @param other The existing instance to copy.
     */
    private Builder(com.gs.atc.bok.schemaRegistry.Transaccion other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.fechaHora)) {
        this.fechaHora = data().deepCopy(fields()[1].schema(), other.fechaHora);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.nombre)) {
        this.nombre = data().deepCopy(fields()[2].schema(), other.nombre);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.accion)) {
        this.accion = data().deepCopy(fields()[3].schema(), other.accion);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.fechaInicioProceso)) {
        this.fechaInicioProceso = data().deepCopy(fields()[4].schema(), other.fechaInicioProceso);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.fechaFinProceso)) {
        this.fechaFinProceso = data().deepCopy(fields()[5].schema(), other.fechaFinProceso);
        fieldSetFlags()[5] = true;
      }
    }

    /**
      * Gets the value of the 'id' field.
      * @return The value.
      */
    public java.lang.CharSequence getId() {
      return id;
    }


    /**
      * Sets the value of the 'id' field.
      * @param value The value of 'id'.
      * @return This builder.
      */
    public com.gs.atc.bok.schemaRegistry.Transaccion.Builder setId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'id' field has been set.
      * @return True if the 'id' field has been set, false otherwise.
      */
    public boolean hasId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'id' field.
      * @return This builder.
      */
    public com.gs.atc.bok.schemaRegistry.Transaccion.Builder clearId() {
      id = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'fechaHora' field.
      * @return The value.
      */
    public java.lang.CharSequence getFechaHora() {
      return fechaHora;
    }


    /**
      * Sets the value of the 'fechaHora' field.
      * @param value The value of 'fechaHora'.
      * @return This builder.
      */
    public com.gs.atc.bok.schemaRegistry.Transaccion.Builder setFechaHora(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.fechaHora = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'fechaHora' field has been set.
      * @return True if the 'fechaHora' field has been set, false otherwise.
      */
    public boolean hasFechaHora() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'fechaHora' field.
      * @return This builder.
      */
    public com.gs.atc.bok.schemaRegistry.Transaccion.Builder clearFechaHora() {
      fechaHora = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'nombre' field.
      * @return The value.
      */
    public java.lang.CharSequence getNombre() {
      return nombre;
    }


    /**
      * Sets the value of the 'nombre' field.
      * @param value The value of 'nombre'.
      * @return This builder.
      */
    public com.gs.atc.bok.schemaRegistry.Transaccion.Builder setNombre(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.nombre = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'nombre' field has been set.
      * @return True if the 'nombre' field has been set, false otherwise.
      */
    public boolean hasNombre() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'nombre' field.
      * @return This builder.
      */
    public com.gs.atc.bok.schemaRegistry.Transaccion.Builder clearNombre() {
      nombre = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'accion' field.
      * @return The value.
      */
    public java.lang.CharSequence getAccion() {
      return accion;
    }


    /**
      * Sets the value of the 'accion' field.
      * @param value The value of 'accion'.
      * @return This builder.
      */
    public com.gs.atc.bok.schemaRegistry.Transaccion.Builder setAccion(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.accion = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'accion' field has been set.
      * @return True if the 'accion' field has been set, false otherwise.
      */
    public boolean hasAccion() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'accion' field.
      * @return This builder.
      */
    public com.gs.atc.bok.schemaRegistry.Transaccion.Builder clearAccion() {
      accion = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'fechaInicioProceso' field.
      * @return The value.
      */
    public java.lang.CharSequence getFechaInicioProceso() {
      return fechaInicioProceso;
    }


    /**
      * Sets the value of the 'fechaInicioProceso' field.
      * @param value The value of 'fechaInicioProceso'.
      * @return This builder.
      */
    public com.gs.atc.bok.schemaRegistry.Transaccion.Builder setFechaInicioProceso(java.lang.CharSequence value) {
      validate(fields()[4], value);
      this.fechaInicioProceso = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'fechaInicioProceso' field has been set.
      * @return True if the 'fechaInicioProceso' field has been set, false otherwise.
      */
    public boolean hasFechaInicioProceso() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'fechaInicioProceso' field.
      * @return This builder.
      */
    public com.gs.atc.bok.schemaRegistry.Transaccion.Builder clearFechaInicioProceso() {
      fechaInicioProceso = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'fechaFinProceso' field.
      * @return The value.
      */
    public java.lang.CharSequence getFechaFinProceso() {
      return fechaFinProceso;
    }


    /**
      * Sets the value of the 'fechaFinProceso' field.
      * @param value The value of 'fechaFinProceso'.
      * @return This builder.
      */
    public com.gs.atc.bok.schemaRegistry.Transaccion.Builder setFechaFinProceso(java.lang.CharSequence value) {
      validate(fields()[5], value);
      this.fechaFinProceso = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'fechaFinProceso' field has been set.
      * @return True if the 'fechaFinProceso' field has been set, false otherwise.
      */
    public boolean hasFechaFinProceso() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'fechaFinProceso' field.
      * @return This builder.
      */
    public com.gs.atc.bok.schemaRegistry.Transaccion.Builder clearFechaFinProceso() {
      fechaFinProceso = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Transaccion build() {
      try {
        Transaccion record = new Transaccion();
        record.id = fieldSetFlags()[0] ? this.id : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.fechaHora = fieldSetFlags()[1] ? this.fechaHora : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.nombre = fieldSetFlags()[2] ? this.nombre : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.accion = fieldSetFlags()[3] ? this.accion : (java.lang.CharSequence) defaultValue(fields()[3]);
        record.fechaInicioProceso = fieldSetFlags()[4] ? this.fechaInicioProceso : (java.lang.CharSequence) defaultValue(fields()[4]);
        record.fechaFinProceso = fieldSetFlags()[5] ? this.fechaFinProceso : (java.lang.CharSequence) defaultValue(fields()[5]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Transaccion>
    WRITER$ = (org.apache.avro.io.DatumWriter<Transaccion>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Transaccion>
    READER$ = (org.apache.avro.io.DatumReader<Transaccion>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.id);

    out.writeString(this.fechaHora);

    out.writeString(this.nombre);

    out.writeString(this.accion);

    out.writeString(this.fechaInicioProceso);

    out.writeString(this.fechaFinProceso);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.id = in.readString(this.id instanceof Utf8 ? (Utf8)this.id : null);

      this.fechaHora = in.readString(this.fechaHora instanceof Utf8 ? (Utf8)this.fechaHora : null);

      this.nombre = in.readString(this.nombre instanceof Utf8 ? (Utf8)this.nombre : null);

      this.accion = in.readString(this.accion instanceof Utf8 ? (Utf8)this.accion : null);

      this.fechaInicioProceso = in.readString(this.fechaInicioProceso instanceof Utf8 ? (Utf8)this.fechaInicioProceso : null);

      this.fechaFinProceso = in.readString(this.fechaFinProceso instanceof Utf8 ? (Utf8)this.fechaFinProceso : null);

    } else {
      for (int i = 0; i < 6; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.id = in.readString(this.id instanceof Utf8 ? (Utf8)this.id : null);
          break;

        case 1:
          this.fechaHora = in.readString(this.fechaHora instanceof Utf8 ? (Utf8)this.fechaHora : null);
          break;

        case 2:
          this.nombre = in.readString(this.nombre instanceof Utf8 ? (Utf8)this.nombre : null);
          break;

        case 3:
          this.accion = in.readString(this.accion instanceof Utf8 ? (Utf8)this.accion : null);
          break;

        case 4:
          this.fechaInicioProceso = in.readString(this.fechaInicioProceso instanceof Utf8 ? (Utf8)this.fechaInicioProceso : null);
          break;

        case 5:
          this.fechaFinProceso = in.readString(this.fechaFinProceso instanceof Utf8 ? (Utf8)this.fechaFinProceso : null);
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










